name: trigger-app
port: 8501

dependencies:
  pypi:
    streamlit: ""
    ob-project-utils: ""
    outerbounds: ""

commands:
  - streamlit run deployments/trigger-app/app.py --server.port 8501 --server.address 0.0.0.0
